version: '3'

services:
  app: 
    build:
      context: ./node
    image: pp5ere/node:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s node index.js
    networks: 
      - nodelan
    volumes:
        - ./node:/usr/src/app
        - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db
      - nginx
  db: 
    build:
      context: ./mysql
    image: pp5ere/mysql:prod
    container_name: db
    restart: always
    #volumes:
    #  - ./mysql/data/:/var/lib/mysql

    networks: 
      - nodelan
  nginx:
    build:
      context: ./nginx
    image: pp5ere/nginx:prod
    container_name: nginx
    networks:
      - nodelan
    ports: 
      - "8080:80"
networks:
  nodelan:
    driver: bridge